const level1 = new Level(
    [
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new SmallChicken(),
        new SmallChicken(),
        new SmallChicken(),
        new SmallChicken(),
        new SmallChicken(),
        new Endboss()
    ],
    [
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud()
    ],
    [
        new BackgroundObject("img/5_background/layers/air.png",-719),
        new BackgroundObject("img/5_background/layers/3_third_layer/2.png", -719),
        new BackgroundObject("img/5_background/layers/2_second_layer/2.png", -719),
        new BackgroundObject("img/5_background/layers/1_first_layer/2.png", -719),


        new BackgroundObject("img/5_background/layers/air.png",0),
        new BackgroundObject("img/5_background/layers/3_third_layer/1.png", 0),
        new BackgroundObject("img/5_background/layers/2_second_layer/1.png", 0),
        new BackgroundObject("img/5_background/layers/1_first_layer/1.png", 0),
        new BackgroundObject("img/5_background/layers/air.png",719),
        new BackgroundObject("img/5_background/layers/3_third_layer/2.png", 719),
        new BackgroundObject("img/5_background/layers/2_second_layer/2.png", 719),
        new BackgroundObject("img/5_background/layers/1_first_layer/2.png", 719),

        new BackgroundObject("img/5_background/layers/air.png",719*2),
        new BackgroundObject("img/5_background/layers/3_third_layer/1.png", 719*2),
        new BackgroundObject("img/5_background/layers/2_second_layer/1.png", 719*2),
        new BackgroundObject("img/5_background/layers/1_first_layer/1.png", 719*2),
        new BackgroundObject("img/5_background/layers/air.png",719*3),
        new BackgroundObject("img/5_background/layers/3_third_layer/2.png", 719*3),
        new BackgroundObject("img/5_background/layers/2_second_layer/2.png", 719*3),
        new BackgroundObject("img/5_background/layers/1_first_layer/2.png", 719*3),

        new BackgroundObject("img/5_background/layers/air.png",719*4),
        new BackgroundObject("img/5_background/layers/3_third_layer/1.png", 719*4),
        new BackgroundObject("img/5_background/layers/2_second_layer/1.png", 719*4),
        new BackgroundObject("img/5_background/layers/1_first_layer/1.png", 719*4),
        new BackgroundObject("img/5_background/layers/air.png",719*5),
        new BackgroundObject("img/5_background/layers/3_third_layer/2.png", 719*5),
        new BackgroundObject("img/5_background/layers/2_second_layer/2.png", 719*5),
        new BackgroundObject("img/5_background/layers/1_first_layer/2.png", 719*5),

        new BackgroundObject("img/5_background/layers/air.png",719*6),
        new BackgroundObject("img/5_background/layers/3_third_layer/1.png", 719*6),
        new BackgroundObject("img/5_background/layers/2_second_layer/1.png", 719*6),
        new BackgroundObject("img/5_background/layers/1_first_layer/1.png", 719*6),
        new BackgroundObject("img/5_background/layers/air.png",719*7),
        new BackgroundObject("img/5_background/layers/3_third_layer/2.png", 719*7),
        new BackgroundObject("img/5_background/layers/2_second_layer/2.png", 719*7),
        new BackgroundObject("img/5_background/layers/1_first_layer/2.png", 719*7),

        new BackgroundObject("img/5_background/layers/air.png",719*8),
        new BackgroundObject("img/5_background/layers/3_third_layer/1.png", 719*8),
        new BackgroundObject("img/5_background/layers/2_second_layer/1.png", 719*8),
        new BackgroundObject("img/5_background/layers/1_first_layer/1.png", 719*8),
        new BackgroundObject("img/5_background/layers/air.png",719*9),
        new BackgroundObject("img/5_background/layers/3_third_layer/2.png", 719*9),
        new BackgroundObject("img/5_background/layers/2_second_layer/2.png", 719*9),
        new BackgroundObject("img/5_background/layers/1_first_layer/2.png", 719*9),

        new BackgroundObject("img/5_background/layers/air.png",719*10),
        new BackgroundObject("img/5_background/layers/3_third_layer/1.png", 719*10),
        new BackgroundObject("img/5_background/layers/2_second_layer/1.png", 719*10),
        new BackgroundObject("img/5_background/layers/1_first_layer/1.png", 719*10),
        new BackgroundObject("img/5_background/layers/air.png",719*11),
        new BackgroundObject("img/5_background/layers/3_third_layer/2.png", 719*11),
        new BackgroundObject("img/5_background/layers/2_second_layer/2.png", 719*11),
        new BackgroundObject("img/5_background/layers/1_first_layer/2.png", 719*11),

        new BackgroundObject("img/5_background/layers/air.png",719*12),
        new BackgroundObject("img/5_background/layers/3_third_layer/1.png", 719*12),
        new BackgroundObject("img/5_background/layers/2_second_layer/1.png", 719*12),
        new BackgroundObject("img/5_background/layers/1_first_layer/1.png", 719*12),
        new BackgroundObject("img/5_background/layers/air.png",719*13),
        new BackgroundObject("img/5_background/layers/3_third_layer/2.png", 719*13),
        new BackgroundObject("img/5_background/layers/2_second_layer/2.png", 719*13),
        new BackgroundObject("img/5_background/layers/1_first_layer/2.png", 719*13)
    ],
    [
        new Coin(200),
        new Coin(300),
        new Coin(400),
        new Coin(500),
        new Coin(600),
        new Coin(700),
        new Coin(800),
        new Coin(900),
        new Coin(1000),
        new Coin(1100)
    ],
    [
        new SalsaBottle(250),
        new SalsaBottle(350),
        new SalsaBottle(450),
        new SalsaBottle(550),
        new SalsaBottle(650),
        new SalsaBottle(750),
        new SalsaBottle(850),
        new SalsaBottle(950),
        new SalsaBottle(1050),
        new SalsaBottle(1150)
    ]
);